layout (local_size_x = X_SIZE, local_size_y = Y_SIZE, local_size_z = Z_SIZE) in;

layout(binding = 0, rgba32f) readonly uniform  image2DArray input_image;
layout(binding = 1, rgba32f) writeonly uniform  image2DArray output_image;

void main(void)
{
    ivec3 pos = ivec3(gl_GlobalInvocationID.xyz);
    vec4 data = imageLoad(input_image, ivec3(0, 0, pos.x));
    imageStore(output_image, pos, data);
}
