layout (local_size_x = X_SIZE, local_size_y = Y_SIZE, local_size_z = Z_SIZE) in;

layout(binding = 0, rgba32f) readonly uniform  image2D input_image;
layout(binding = 1, rgba32f) writeonly uniform  image2D output_image;

void main(void)
{
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    vec4 data = imageLoad(input_image, pos);
    data.r = tanh(data.r);
    data.g = tanh(data.g);
    data.b = tanh(data.b);
    data.a = tanh(data.a);
    imageStore(output_image, pos.xy, data);
}
